var _a;
//import * as BUI from "@thatopen/ui";
import * as OBC from "@thatopen/components";
const container = (_a = document.getElementById("container")) !== null && _a !== void 0 ? _a : document.body;
const components = new OBC.Components();
const worlds = components.get(OBC.Worlds);
const world = worlds.create();
world.scene = new OBC.SimpleScene(components);
world.renderer = new OBC.SimpleRenderer(components, container);
world.camera = new OBC.SimpleCamera(components);
components.init();
world.camera.controls.setLookAt(12, 6, 8, 0, 0, -10);
world.scene.setup();
const grids = components.get(OBC.Grids);
grids.create(world);
